sonar.projectKey=tanaya-agre_infra-monitoring-devsecops
sonar.organization=tanaya-agre
sonar.sources=dashboard
sonar.host.url=https://sonarcloud.io
sonar.python.version=3.13
sonar.exclusions=dashboard/static/**,**/*.html,**/__pycache__/**,**/.pytest_cache/**
